services:
  - type: web
    name: grow-a-garden-stock-tracker
    env: docker
    region: frankfurt  # Европейский регион для лучшей производительности
    plan: free  # Бесплатный план
    healthCheckPath: /api/status  # Путь для проверки здоровья сервиса
    numInstances: 1  # Количество инстансов
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
    autoDeploy: true  # Автоматический деплой при пуше в main
    domains:
      - grow-garden-tracker.onrender.com  # Ваш поддомен на render.com
